//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoDeEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computador()
        {
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int Id_Computador { get; set; }
        public string Serial { get; set; }
        public int Id_Funcionario { get; set; }
        public string Ciudad { get; set; }
        public string Marca { get; set; }
        public int Id_Tipo_Computador { get; set; }
        public string Modelo { get; set; }
        public string Procesador { get; set; }
        public string Memoria_Ram { get; set; }
        public string Disco_Duro { get; set; }
        public string Sistema_Operativo { get; set; }
        public bool Estado { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual TipoComputador TipoComputador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
