//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantenimientoDeEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int Id_Mantenimiento { get; set; }
        public int Id_Computador { get; set; }
        public System.DateTime UltimoMantenimiento { get; set; }
        public System.DateTime ProximoMantenimiento { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Computador Computador { get; set; }
    }
}
